<?php

use App\Actions\Learner\DeleteLearner;
use App\Actions\RecurringSlots\CreateRecurringSlot;
use App\Actions\RecurringSlots\EndRecurringSlot;
use App\Actions\RecurringSlots\PauseRecurringSlot;
use App\Enums\CurriculumCode;
use App\Enums\LessonCancelReason;
use App\Enums\LessonStatus;
use App\Enums\LevelTier;
use App\Enums\RecurringSlotStatus;
use App\Enums\Role;
use App\Enums\TutorProfileStatus;
use App\Exceptions\LearnerDeletionException;
use App\Mail\Lessons\LessonSkippedMail;
use App\Mail\RecurringSlots\RecurringSlotCreatedMail;
use App\Mail\RecurringSlots\RecurringSlotEndedMail;
use App\Mail\RecurringSlots\RecurringSlotPausedMail;
use App\Models\AuditLog;
use App\Models\AvailabilityRule;
use App\Models\Curriculum;
use App\Models\Learner;
use App\Models\Lesson;
use App\Models\PaymentMethod;
use App\Models\PriceBand;
use App\Models\RecurringSlot;
use App\Models\Subject;
use App\Models\TutorProfile;
use App\Models\TutorStrike;
use App\Models\TutorSubject;
use App\Models\User;
use App\Services\Lessons\LessonStateMachine;
use App\Support\Facades\Settings;
use Carbon\CarbonImmutable;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Mail;

/**
 * CP4 (4d): the parent and tutor screens for weekly slots, the fake add-card page, and the R102
 * emails. "Now" is Monday 2026-09-14 06:00 UTC; the default lead is 12 hours.
 */
beforeEach(function () {
    $this->travelTo(CarbonImmutable::parse('2026-09-14 06:00:00', 'UTC'));
});

/**
 * A bookable tutor who teaches one subject and is available on one weekday.
 *
 * @return array{tutor: TutorProfile, curriculum_id: int, subject_id: int}
 */
function wpTutor(string $timezone = 'UTC', string $from = '09:00:00', string $to = '12:00:00', int $weekday = 2): array
{
    $curriculum = Curriculum::query()->firstOrCreate(['code' => CurriculumCode::Gcse], ['name' => CurriculumCode::Gcse->value, 'sort' => 0]);
    $subject = Subject::factory()->create();
    $tutor = TutorProfile::factory()->approved()->create(['hourly_rate' => 10000]);

    TutorSubject::factory()->create([
        'tutor_profile_id' => $tutor->id,
        'curriculum_id' => $curriculum->id,
        'subject_id' => $subject->id,
        'level_tier' => LevelTier::LowerSecondary,
    ]);

    PriceBand::query()->firstOrCreate(
        ['curriculum_id' => $curriculum->id, 'level_tier' => LevelTier::LowerSecondary, 'effective_from' => '2000-01-01'],
        ['min_rate' => 5000, 'max_rate' => 20000],
    );

    AvailabilityRule::factory()->create([
        'tutor_profile_id' => $tutor->id, 'weekday' => $weekday, 'start_time' => $from, 'end_time' => $to, 'timezone' => $timezone,
    ]);

    return ['tutor' => $tutor->fresh(), 'curriculum_id' => $curriculum->id, 'subject_id' => $subject->id];
}

/**
 * A parent with one learner, optionally a saved card and a completed trial with the tutor.
 *
 * @return array{parent: User, learner: Learner}
 */
function wpParent(TutorProfile $tutor, bool $trial = true, bool $card = true, string $timezone = 'UTC'): array
{
    $parent = User::factory()->create(['timezone' => $timezone]);
    $learner = Learner::factory()->create(['account_user_id' => $parent->id, 'curriculum_id' => gcseCurriculumId()]);

    if ($card) {
        PaymentMethod::factory()->create(['account_user_id' => $parent->id]);
    }

    if ($trial) {
        static $offset = 0;
        $at = now()->subDays(3)->subHours(++$offset);

        Lesson::factory()->trial()->withStatus(LessonStatus::Completed)->create([
            'tutor_profile_id' => $tutor->id,
            'learner_id' => $learner->id,
            'starts_at' => $at,
            'ends_at' => $at->addHour(),
        ]);
    }

    return ['parent' => $parent, 'learner' => $learner];
}

/**
 * @param  array<string, mixed>  $extra
 * @return array<string, mixed>
 */
function wpForm(array $setup, Learner $learner, array $extra = []): array
{
    return array_merge([
        'learner_id' => $learner->id,
        'tutor_id' => $setup['tutor']->id,
        'curriculum_id' => $setup['curriculum_id'],
        'subject_id' => $setup['subject_id'],
        'weekday' => 2,
        'start_time' => '10:00',
        'starts_on' => '2026-09-22',
    ], $extra);
}

/**
 * A live slot on the setup's tutor with reserved lessons generated by the real job.
 *
 * @return array{slot: RecurringSlot, parent: User, learner: Learner, setup: array<string, mixed>}
 */
function wpSlotWithLessons(): array
{
    $setup = wpTutor();
    ['parent' => $parent, 'learner' => $learner] = wpParent($setup['tutor']);

    $slot = RecurringSlot::factory()->create([
        'learner_id' => $learner->id,
        'tutor_profile_id' => $setup['tutor']->id,
        'curriculum_id' => $setup['curriculum_id'],
        'subject_id' => $setup['subject_id'],
        'weekday' => 2,
        'start_time' => '10:00:00',
        'timezone' => 'UTC',
        'starts_on' => '2026-09-14',
        'generated_until' => '2026-09-13',
        'price' => 10000,
    ]);

    Artisan::call('recurring:generate');

    return ['slot' => $slot->fresh(), 'parent' => $parent, 'learner' => $learner, 'setup' => $setup];
}

// --- the fake add-card page (R100) --------------------------------------------------------

it('shows the test-card page with two named cards and no card-number or CVC field', function () {
    $setup = wpTutor();
    ['parent' => $parent] = wpParent($setup['tutor'], card: false);

    test()->actingAs($parent)->get(route('payment-methods.create', ['tutor' => $setup['tutor']->id]))
        ->assertOk()
        ->assertInertia(fn ($page) => $page->component('payment-methods/Create')
            ->has('cards', 2)
            ->where('current', null)
            ->where('tutor', $setup['tutor']->id)
            ->missing('number')->missing('cvc'));

    expect(file_get_contents(resource_path('js/pages/payment-methods/Create.vue')))
        ->toContain('<TestModeBanner')
        ->not->toMatch('/cvc|cvv|card-number|type="number"/i');
});

it('saves the chosen test card as the only card, replaces it on a second save, and audits it', function () {
    $setup = wpTutor();
    ['parent' => $parent] = wpParent($setup['tutor'], card: false);

    test()->actingAs($parent)->post(route('payment-methods.store'), ['card' => 'succeeds', 'tutor' => $setup['tutor']->id])
        ->assertRedirect(route('weekly-slots.create', ['tutor' => $setup['tutor']->id]));

    $card = PaymentMethod::query()->where('account_user_id', $parent->id)->sole();
    expect($card->gateway_token)->toStartWith('fake_pm_succeeds_')
        ->and($card->last4)->toBe('4242')
        ->and($card->isUsable())->toBeTrue();

    test()->actingAs($parent)->post(route('payment-methods.store'), ['card' => 'declines'])
        ->assertRedirect(route('learners.index'));

    $card = PaymentMethod::query()->where('account_user_id', $parent->id)->sole();
    expect($card->gateway_token)->toStartWith('fake_pm_declines_')
        ->and($card->last4)->toBe('0002')
        ->and(AuditLog::query()->where('action', 'payment_method.saved')->count())->toBe(2);
});

it('rejects an unknown card choice and typed card data', function () {
    $setup = wpTutor();
    ['parent' => $parent] = wpParent($setup['tutor'], card: false);

    test()->actingAs($parent)->post(route('payment-methods.store'), ['card' => '4242424242424242'])
        ->assertSessionHasErrors('card');

    expect(PaymentMethod::query()->where('account_user_id', $parent->id)->exists())->toBeFalse();
});

it('404s the test-card page on both routes in production', function () {
    $setup = wpTutor();
    ['parent' => $parent] = wpParent($setup['tutor'], card: false);

    app()->detectEnvironment(fn () => 'production');

    test()->actingAs($parent)->get(route('payment-methods.create'))->assertNotFound();
    test()->actingAs($parent)->withSession(['_token' => 't'])->post(route('payment-methods.store'), ['card' => 'succeeds', '_token' => 't'])->assertNotFound();

    expect(PaymentMethod::query()->count())->toBe(0);
});

it('keeps the test-card page to signed-in parents', function () {
    $setup = wpTutor();

    test()->get(route('payment-methods.create'))->assertRedirect(route('login'));
    test()->actingAs($setup['tutor']->user)->get(route('payment-methods.create'))->assertForbidden();
});

// --- setting a slot up (R96) --------------------------------------------------------------

it('offers the tutor\'s whole hours as weekly options and leaves out an hour another slot holds', function () {
    $setup = wpTutor();
    ['parent' => $parent] = wpParent($setup['tutor']);

    RecurringSlot::factory()->create([
        'tutor_profile_id' => $setup['tutor']->id, 'weekday' => 2, 'start_time' => '10:00:00', 'timezone' => 'UTC',
    ]);
    RecurringSlot::factory()->ended()->create([
        'tutor_profile_id' => $setup['tutor']->id, 'weekday' => 2, 'start_time' => '11:00:00', 'timezone' => 'UTC',
    ]);

    test()->actingAs($parent)->get(route('weekly-slots.create', ['tutor' => $setup['tutor']->id]))
        ->assertOk()
        ->assertInertia(fn ($page) => $page->component('weekly-slots/Create')
            ->has('options', 2)
            ->where('options.0.value', '2|09:00')
            ->where('options.1.value', '2|11:00')
            ->where('options.0.label', 'Tuesday 09:00 (UTC)')
            ->where('can_add_card', true)
            ->where('card.last4', fn ($last4) => is_string($last4))
            ->has('subjects', 1));
});

it('shows the next occurrence in the parent\'s own timezone, where the weekday can differ', function () {
    // Tuesday 02:00 in Karachi (UTC+5) is Monday 21:00 UTC, so a west-of-UTC parent sees Monday.
    $setup = wpTutor('Asia/Karachi', '02:00:00', '04:00:00');

    ['parent' => $la] = wpParent($setup['tutor'], timezone: 'America/Los_Angeles');
    ['parent' => $dubai] = wpParent($setup['tutor'], timezone: 'Asia/Dubai');

    test()->actingAs($la)->get(route('weekly-slots.create', ['tutor' => $setup['tutor']->id]))
        ->assertInertia(fn ($page) => $page->where('options.0.label', 'Tuesday 02:00 (Asia/Karachi)')
            ->where('options.0.next', 'Mon, 14 Sep 2026, 2:00 PM'));

    test()->actingAs($dubai)->get(route('weekly-slots.create', ['tutor' => $setup['tutor']->id]))
        ->assertInertia(fn ($page) => $page->where('options.0.next', 'Tue, 15 Sep 2026, 1:00 AM'));
});

it('explains the trial prerequisite, and offers the add-card step when no card is saved', function () {
    $setup = wpTutor();
    ['parent' => $parent, 'learner' => $learner] = wpParent($setup['tutor'], trial: false, card: false);

    test()->actingAs($parent)->get(route('weekly-slots.create', ['tutor' => $setup['tutor']->id]))
        ->assertInertia(fn ($page) => $page->where('card', null)
            ->where('selected_learner', $learner->id)
            ->where('learners.0.trial_completed', false));
});

it('404s the setup page for a tutor who is not bookable, and ignores another parent\'s learner id', function () {
    $setup = wpTutor();
    ['parent' => $parent] = wpParent($setup['tutor']);
    ['learner' => $stranger] = wpParent($setup['tutor']);

    $hidden = TutorProfile::factory()->create();
    test()->actingAs($parent)->get(route('weekly-slots.create', ['tutor' => $hidden->id]))->assertNotFound();

    test()->actingAs($parent)->get(route('weekly-slots.create', ['tutor' => $setup['tutor']->id, 'learner' => $stranger->id]))
        ->assertInertia(fn ($page) => $page->has('learners', 1)->where('learners.0.id', fn ($id) => $id !== $stranger->id));
});

it('creates the slot, freezes the tutor\'s rate, lands on the learner page and emails both parties', function () {
    Mail::fake();
    $setup = wpTutor();
    ['parent' => $parent, 'learner' => $learner] = wpParent($setup['tutor']);

    test()->actingAs($parent)->post(route('weekly-slots.store'), wpForm($setup, $learner, ['ends_on' => '2026-12-01']))
        ->assertRedirect(route('learners.show', $learner));

    $slot = RecurringSlot::query()->sole();
    expect($slot->status)->toBe(RecurringSlotStatus::Active)
        ->and($slot->price->toFils())->toBe(10000)
        ->and($slot->ends_on->toDateString())->toBe('2026-12-01')
        ->and($slot->created_by_user_id)->toBe($parent->id);

    Mail::assertQueued(RecurringSlotCreatedMail::class, fn ($m) => $m->hasTo($parent->email));
    Mail::assertQueued(RecurringSlotCreatedMail::class, fn ($m) => $m->hasTo($setup['tutor']->user->email));
    Mail::assertQueued(RecurringSlotCreatedMail::class, 2);
});

it('refuses a slot before the trial is complete, with the reason on the form', function () {
    Mail::fake();
    $setup = wpTutor();
    ['parent' => $parent, 'learner' => $learner] = wpParent($setup['tutor'], trial: false);

    test()->actingAs($parent)->post(route('weekly-slots.store'), wpForm($setup, $learner))
        ->assertSessionHasErrors('slot');

    expect(RecurringSlot::query()->count())->toBe(0);
    Mail::assertNothingQueued();
});

it('refuses to set a slot up for another parent\'s learner', function () {
    Mail::fake();
    $setup = wpTutor();
    ['parent' => $parent] = wpParent($setup['tutor']);
    ['learner' => $stranger] = wpParent($setup['tutor']);

    test()->actingAs($parent)->post(route('weekly-slots.store'), wpForm($setup, $stranger))
        ->assertSessionHasErrors('slot');

    expect(RecurringSlot::query()->count())->toBe(0);
    Mail::assertNothingQueued();
});

it('reports a clash with another slot as a form error rather than a server error', function () {
    $setup = wpTutor();
    ['parent' => $first, 'learner' => $firstLearner] = wpParent($setup['tutor']);
    ['parent' => $second, 'learner' => $secondLearner] = wpParent($setup['tutor']);

    test()->actingAs($first)->post(route('weekly-slots.store'), wpForm($setup, $firstLearner))->assertRedirect();
    test()->actingAs($second)->post(route('weekly-slots.store'), wpForm($setup, $secondLearner))->assertSessionHasErrors('slot');

    expect(RecurringSlot::query()->count())->toBe(1);
});

it('validates the shape of the setup form', function () {
    $setup = wpTutor();
    ['parent' => $parent, 'learner' => $learner] = wpParent($setup['tutor']);

    test()->actingAs($parent)->post(route('weekly-slots.store'), wpForm($setup, $learner, ['weekday' => 9, 'start_time' => '10:30', 'ends_on' => '2026-09-01']))
        ->assertSessionHasErrors(['weekday', 'start_time', 'ends_on']);
});

it('lets an admin create the slot through the action with the trial override, and still emails both parties', function () {
    Mail::fake();
    $setup = wpTutor();
    ['learner' => $learner] = wpParent($setup['tutor'], trial: false);
    $admin = User::factory()->admin()->create();

    app(CreateRecurringSlot::class)($admin, $learner, $setup['tutor'], [
        'curriculum_id' => $setup['curriculum_id'], 'subject_id' => $setup['subject_id'], 'weekday' => 2, 'start_time' => '10:00', 'starts_on' => '2026-09-22',
    ], 'goodwill');

    Mail::assertQueued(RecurringSlotCreatedMail::class, 2);
});

// --- the learner page ---------------------------------------------------------------------

it('lists the learner\'s slots, upcoming weekly lessons with Skip on reserved ones, and tutors to set a slot up with', function () {
    ['slot' => $slot, 'parent' => $parent, 'learner' => $learner, 'setup' => $setup] = wpSlotWithLessons();

    test()->actingAs($parent)->get(route('learners.show', $learner))
        ->assertOk()
        ->assertInertia(fn ($page) => $page->component('learners/Show')
            ->has('slots', 1)
            ->where('slots.0.id', $slot->id)
            ->where('slots.0.status', 'active')
            ->where('slots.0.schedule', 'Tuesday 10:00 (UTC)')
            ->where('slots.0.next', 'Tue, 15 Sep 2026, 10:00 AM')
            ->where('lessons.0.cancel_kind', 'skip')
            ->has('eligible_tutors', 0));

    // Once the slot ends, the tutor is offered again.
    app(EndRecurringSlot::class)($parent, $slot);

    test()->actingAs($parent)->get(route('learners.show', $learner))
        ->assertInertia(fn ($page) => $page->where('slots.0.status', 'ended')->where('slots.0.next', null)
            ->has('lessons', 0)
            ->has('eligible_tutors', 1)
            ->where('eligible_tutors.0.id', $setup['tutor']->id));
});

it('keeps the learner page to the owning parent', function () {
    $setup = wpTutor();
    ['learner' => $learner] = wpParent($setup['tutor']);
    ['parent' => $other] = wpParent($setup['tutor']);

    test()->actingAs($other)->get(route('learners.show', $learner))->assertForbidden();
    auth()->logout();
    test()->get(route('learners.show', $learner))->assertRedirect(route('login'));
});

it('marks generated lessons as weekly on both dashboards, and shows the tutor their slots as fixed blocks', function () {
    ['slot' => $slot, 'parent' => $parent, 'setup' => $setup] = wpSlotWithLessons();

    test()->actingAs($parent)->get(route('dashboard'))
        ->assertInertia(fn ($page) => $page->where('upcoming.0.weekly', true));

    test()->actingAs($setup['tutor']->user)->get(route('tutor.dashboard'))
        ->assertInertia(fn ($page) => $page->has('slots', 1)
            ->where('slots.0.id', $slot->id)
            ->where('slots.0.schedule', 'Tuesday 10:00 (UTC)')
            ->where('slots.0.ending_on', null)
            ->where('upcoming.0.weekly', true));
});

it('offers the weekly-slot entry on a tutor profile to a signed-in parent only', function () {
    $setup = wpTutor();
    ['parent' => $parent] = wpParent($setup['tutor']);

    test()->get(route('tutors.show', $setup['tutor']->id))
        ->assertOk()->assertInertia(fn ($page) => $page->where('can_set_up_weekly', false));

    test()->actingAs($parent)->get(route('tutors.show', $setup['tutor']->id))
        ->assertInertia(fn ($page) => $page->where('can_set_up_weekly', true));
});

// --- ending a slot (R99) ------------------------------------------------------------------

it('shows the parent what ending releases and what stays, then ends the slot at once', function () {
    Mail::fake();
    ['slot' => $slot, 'parent' => $parent, 'learner' => $learner, 'setup' => $setup] = wpSlotWithLessons();

    $lessons = Lesson::query()->where('recurring_slot_id', $slot->id)->orderBy('starts_at')->get();
    $paid = $lessons->first();
    LessonStateMachine::transition($paid, LessonStatus::Confirmed);
    $reserved = $lessons->count() - 1;

    test()->actingAs($parent)->get(route('weekly-slots.end.show', $slot))
        ->assertOk()
        ->assertInertia(fn ($page) => $page->component('weekly-slots/End')
            ->where('reserved_count', $reserved)
            ->has('confirmed', 1)
            ->where('confirmed.0.id', $paid->id)
            ->where('weekly_slot.ended', false));

    test()->actingAs($parent)->post(route('weekly-slots.end', $slot))
        ->assertRedirect(route('learners.show', $learner));

    expect($slot->fresh()->status)->toBe(RecurringSlotStatus::Ended)
        ->and($paid->fresh()->status)->toBe(LessonStatus::Confirmed)
        ->and(Lesson::query()->where('recurring_slot_id', $slot->id)->where('status', LessonStatus::CancelledByParent)->count())->toBe($reserved)
        ->and(Lesson::query()->where('recurring_slot_id', $slot->id)->where('cancel_reason', LessonCancelReason::SlotEnded->value)->count())->toBe($reserved);

    // One email per party, none per released lesson.
    Mail::assertQueued(RecurringSlotEndedMail::class, 2);
    Mail::assertQueued(RecurringSlotEndedMail::class, fn ($m) => $m->hasTo($setup['tutor']->user->email) && $m->paidLessonsRemaining === 1 && $m->releasedLessons === $reserved);
    Mail::assertNotQueued(LessonSkippedMail::class);
});

it('says a parent-ended slot was ended by the parent, and a tutor-ended one when it stops', function () {
    ['slot' => $slot, 'parent' => $parent] = wpSlotWithLessons();

    $mail = new RecurringSlotEndedMail($slot, $parent, Role::AccountOwner, 3, 0);
    expect($mail->render())->toContain('has been ended from the parent\'s account')->toContain('3 lessons that had not yet been charged');

    $slot->forceFill(['end_effective_on' => '2026-10-05'])->save();
    $mail = new RecurringSlotEndedMail($slot->fresh(), $parent, Role::Tutor, 1, 0);
    expect($mail->render())->toContain('will end after Monday, 5 Oct 2026');
});

it('keeps ending a slot to its own parent', function () {
    ['slot' => $slot] = wpSlotWithLessons();
    $setup = wpTutor();
    ['parent' => $other] = wpParent($setup['tutor']);

    test()->actingAs($other)->get(route('weekly-slots.end.show', $slot))->assertForbidden();
    test()->actingAs($other)->post(route('weekly-slots.end', $slot))->assertForbidden();

    expect($slot->fresh()->status)->toBe(RecurringSlotStatus::Active);
});

it('tells the parent when the slot has already ended, without ending anything twice', function () {
    Mail::fake();
    ['slot' => $slot, 'parent' => $parent] = wpSlotWithLessons();

    test()->actingAs($parent)->post(route('weekly-slots.end', $slot))->assertRedirect();
    Mail::assertQueued(RecurringSlotEndedMail::class, 2);

    test()->actingAs($parent)->get(route('weekly-slots.end.show', $slot))
        ->assertInertia(fn ($page) => $page->where('weekly_slot.ended', true));
    test()->actingAs($parent)->post(route('weekly-slots.end', $slot))->assertRedirect();

    Mail::assertQueued(RecurringSlotEndedMail::class, 2);
});

it('lets the tutor end with notice: the slot runs on, later reserved lessons are released, no strike', function () {
    Mail::fake();
    ['slot' => $slot, 'parent' => $parent, 'setup' => $setup] = wpSlotWithLessons();
    $tutor = $setup['tutor']->user;
    $days = (int) Settings::get('recurring_tutor_end_notice_days');
    $lastDay = CarbonImmutable::now('UTC')->startOfDay()->addDays($days);

    test()->actingAs($tutor)->get(route('tutor.weekly-slots.end.show', $slot))
        ->assertOk()
        ->assertInertia(fn ($page) => $page->component('tutor/EndWeeklySlot')
            ->where('notice_days', $days)
            ->where('last_day', $lastDay->format('D, j M Y'))
            ->where('weekly_slot.notice_given', false));

    $cutoff = $lastDay->endOfDay();
    $expectedReleased = Lesson::query()->where('recurring_slot_id', $slot->id)->where('status', LessonStatus::Reserved)->where('starts_at', '>', $cutoff)->count();
    expect($expectedReleased)->toBeGreaterThan(0);

    test()->actingAs($tutor)->get(route('tutor.weekly-slots.end.show', $slot))
        ->assertInertia(fn ($page) => $page->where('released_count', $expectedReleased));

    test()->actingAs($tutor)->post(route('tutor.weekly-slots.end', $slot))->assertRedirect(route('tutor.dashboard'));

    $slot = $slot->fresh();
    expect($slot->status)->toBe(RecurringSlotStatus::Active)
        ->and($slot->end_effective_on->toDateString())->toBe($lastDay->toDateString())
        ->and($slot->ended_by_user_id)->toBe($tutor->id)
        ->and(TutorStrike::query()->count())->toBe(0)
        ->and(Lesson::query()->where('recurring_slot_id', $slot->id)->where('status', LessonStatus::CancelledByTutor)->where('starts_at', '<=', $cutoff)->count())->toBe(0)
        ->and(Lesson::query()->where('recurring_slot_id', $slot->id)->where('status', LessonStatus::CancelledByTutor)->where('cancel_reason', LessonCancelReason::SlotEnded->value)->where('starts_at', '>', $cutoff)->count())->toBe($expectedReleased);

    Mail::assertQueued(RecurringSlotEndedMail::class, fn ($m) => $m->hasTo($parent->email) && $m->endedBy === Role::Tutor);
    Mail::assertNotQueued(LessonSkippedMail::class);

    // The dashboard block now says it is ending, and a second notice is refused.
    test()->actingAs($tutor)->get(route('tutor.dashboard'))
        ->assertInertia(fn ($page) => $page->where('slots.0.ending_on', $lastDay->format('D, j M Y')));
    test()->actingAs($tutor)->get(route('tutor.weekly-slots.end.show', $slot))
        ->assertInertia(fn ($page) => $page->where('weekly_slot.notice_given', true));

    // A second notice changes nothing and sends nothing more.
    test()->actingAs($tutor)->post(route('tutor.weekly-slots.end', $slot))->assertRedirect(route('tutor.dashboard'));
    expect($slot->fresh()->end_effective_on->toDateString())->toBe($lastDay->toDateString());
    Mail::assertQueued(RecurringSlotEndedMail::class, 2);
});

it('keeps the tutor end screens to that slot\'s tutor, and the parent screens to parents', function () {
    ['slot' => $slot, 'parent' => $parent] = wpSlotWithLessons();
    $other = wpTutor()['tutor']->user;

    test()->actingAs($other)->get(route('tutor.weekly-slots.end.show', $slot))->assertForbidden();
    test()->actingAs($other)->post(route('tutor.weekly-slots.end', $slot))->assertForbidden();
    test()->actingAs($parent)->get(route('tutor.weekly-slots.end.show', $slot))->assertForbidden();
    test()->actingAs($other)->get(route('weekly-slots.end.show', $slot))->assertForbidden();

    expect($slot->fresh()->ended_by_user_id)->toBeNull();
});

// --- skips, pauses and the per-lesson emails ----------------------------------------------

it('lets a parent skip one occurrence, emails as before, and does not refill it on the next run', function () {
    Mail::fake();
    ['slot' => $slot, 'parent' => $parent] = wpSlotWithLessons();

    $lesson = Lesson::query()->where('recurring_slot_id', $slot->id)->orderBy('starts_at')->first();
    $count = Lesson::query()->where('recurring_slot_id', $slot->id)->count();

    test()->actingAs($parent)->post(route('lessons.cancel', $lesson))->assertRedirect();

    expect($lesson->fresh()->status)->toBe(LessonStatus::CancelledByParent);
    Mail::assertQueued(LessonSkippedMail::class, 2);

    Artisan::call('recurring:generate');

    expect(Lesson::query()->where('recurring_slot_id', $slot->id)->count())->toBe($count)
        ->and(Lesson::query()->where('recurring_slot_id', $slot->id)->where('starts_at', $lesson->starts_at)->count())->toBe(1);
});

it('sends one paused email per party instead of a skip email per released lesson', function () {
    Mail::fake();
    ['slot' => $slot, 'parent' => $parent, 'setup' => $setup] = wpSlotWithLessons();
    $admin = User::factory()->admin()->create();

    app(PauseRecurringSlot::class)($admin, $slot);

    Mail::assertQueued(RecurringSlotPausedMail::class, 2);
    Mail::assertQueued(RecurringSlotPausedMail::class, fn ($m) => $m->hasTo($parent->email));
    Mail::assertQueued(RecurringSlotPausedMail::class, fn ($m) => $m->hasTo($setup['tutor']->user->email));
    Mail::assertNotQueued(LessonSkippedMail::class);
});

// --- deleting a learner -------------------------------------------------------------------

it('refuses to remove a minor with a live weekly slot, and allows it once the slot has ended', function () {
    $setup = wpTutor();
    $parent = User::factory()->create();
    $learner = Learner::factory()->create(['account_user_id' => $parent->id, 'is_minor' => true, 'curriculum_id' => gcseCurriculumId()]);
    $slot = RecurringSlot::factory()->create(['learner_id' => $learner->id, 'tutor_profile_id' => $setup['tutor']->id]);

    expect(fn () => app(DeleteLearner::class)($parent, $learner))->toThrow(LearnerDeletionException::class, 'weekly slot');
    expect($learner->fresh()->trashed())->toBeFalse();

    $slot->forceFill(['status' => RecurringSlotStatus::Paused])->save();
    expect(fn () => app(DeleteLearner::class)($parent, $learner))->toThrow(LearnerDeletionException::class);

    $slot->forceFill(['status' => RecurringSlotStatus::Ended])->save();
    app(DeleteLearner::class)($parent, $learner);

    expect(Learner::withTrashed()->find($learner->id)->trashed())->toBeTrue();
});

// --- the model's own schedule maths -------------------------------------------------------

it('finds the next occurrence after an instant, in UTC, honouring the start and end dates', function () {
    $slot = new RecurringSlot([
        'weekday' => 2, 'start_time' => '17:00:00', 'timezone' => 'Asia/Karachi',
        'starts_on' => '2026-09-14', 'ends_on' => '2026-09-22',
    ]);

    // Tuesday 17:00 PKT = 12:00Z.
    expect($slot->nextOccurrenceAfter(CarbonImmutable::parse('2026-09-14 06:00:00', 'UTC'))->toIso8601String())->toBe('2026-09-15T12:00:00+00:00')
        // Strictly after: at the occurrence itself, the next week's.
        ->and($slot->nextOccurrenceAfter(CarbonImmutable::parse('2026-09-15 12:00:00', 'UTC'))->toIso8601String())->toBe('2026-09-22T12:00:00+00:00')
        // Past the end date there is none.
        ->and($slot->nextOccurrenceAfter(CarbonImmutable::parse('2026-09-22 12:00:00', 'UTC')))->toBeNull()
        ->and($slot->scheduleLabel())->toBe('Tuesday 17:00 (Asia/Karachi)');

    $starts = new RecurringSlot(['weekday' => 2, 'start_time' => '17:00:00', 'timezone' => 'UTC', 'starts_on' => '2026-10-06']);
    expect($starts->nextOccurrenceAfter(CarbonImmutable::parse('2026-09-14 06:00:00', 'UTC'))->toDateString())->toBe('2026-10-06');
});

it('keeps the next occurrence on wall-clock time across a daylight-saving change', function () {
    $slot = new RecurringSlot(['weekday' => 0, 'start_time' => '17:00:00', 'timezone' => 'Europe/London', 'starts_on' => '2026-10-01']);

    // Sunday 18 Oct is still BST (17:00 = 16:00Z); Sunday 25 Oct is GMT (17:00 = 17:00Z).
    expect($slot->nextOccurrenceAfter(CarbonImmutable::parse('2026-10-14 00:00:00', 'UTC'))->toIso8601String())->toBe('2026-10-18T16:00:00+00:00')
        ->and($slot->nextOccurrenceAfter(CarbonImmutable::parse('2026-10-18 16:00:00', 'UTC'))->toIso8601String())->toBe('2026-10-25T17:00:00+00:00');
});

// --- review fixes: default start date, refusal wording, tutor notice then parent end -------

it('gives each option the local date of its first lesson, so the default start date is never refused', function () {
    Mail::fake();
    // Monday 17:00 is 11 hours away at 06:00 Monday, inside the 12-hour lead, so the first lesson is next Monday.
    $setup = wpTutor('UTC', '17:00:00', '18:00:00', 1);
    ['parent' => $parent, 'learner' => $learner] = wpParent($setup['tutor']);

    test()->actingAs($parent)->get(route('weekly-slots.create', ['tutor' => $setup['tutor']->id]))
        ->assertInertia(fn ($page) => $page->where('options.0.value', '1|17:00')
            ->where('options.0.first_on', '2026-09-21')
            ->where('min_start', '2026-09-14'));

    // Today's date lands the first lesson inside the lead time; the option's own date does not.
    test()->actingAs($parent)->post(route('weekly-slots.store'), wpForm($setup, $learner, ['weekday' => 1, 'start_time' => '17:00', 'starts_on' => '2026-09-14']))
        ->assertSessionHasErrors('slot');
    test()->actingAs($parent)->post(route('weekly-slots.store'), wpForm($setup, $learner, ['weekday' => 1, 'start_time' => '17:00', 'starts_on' => '2026-09-21']))
        ->assertRedirect(route('learners.show', $learner));

    expect(RecurringSlot::query()->count())->toBe(1);
});

it('reads first_on in the tutor\'s zone, not the parent\'s or UTC', function () {
    // Tuesday 02:00 in Karachi is Monday 21:00 UTC; the tutor-zone date is Tuesday the 15th.
    $setup = wpTutor('Asia/Karachi', '02:00:00', '04:00:00');
    ['parent' => $parent, 'learner' => $learner] = wpParent($setup['tutor'], timezone: 'America/Los_Angeles');

    test()->actingAs($parent)->get(route('weekly-slots.create', ['tutor' => $setup['tutor']->id]))
        ->assertInertia(fn ($page) => $page->where('options.0.first_on', '2026-09-15')
            ->where('options.0.next', 'Mon, 14 Sep 2026, 2:00 PM'));

    test()->actingAs($parent)->post(route('weekly-slots.store'), wpForm($setup, $learner, ['start_time' => '02:00', 'starts_on' => '2026-09-15']))
        ->assertRedirect(route('learners.show', $learner));
});

it('refuses every setup that is not the caller\'s with the same generic message', function () {
    $setup = wpTutor();
    ['parent' => $parent] = wpParent($setup['tutor']);
    ['learner' => $stranger] = wpParent($setup['tutor']);
    ['learner' => $removed] = wpParent($setup['tutor']);
    $removed->delete();

    $generic = 'That weekly slot cannot be set up.';

    foreach ([$stranger->id, $removed->id, 999999] as $id) {
        test()->actingAs($parent)->post(route('weekly-slots.store'), wpForm($setup, $stranger, ['learner_id' => $id]))
            ->assertSessionHasErrors(['slot' => $generic]);
    }

    expect(RecurringSlot::query()->count())->toBe(0);
});

it('lets the parent end at once after the tutor gave notice, and drops the notice date', function () {
    Mail::fake();
    ['slot' => $slot, 'parent' => $parent, 'learner' => $learner, 'setup' => $setup] = wpSlotWithLessons();

    test()->actingAs($setup['tutor']->user)->post(route('tutor.weekly-slots.end', $slot))->assertRedirect();
    $releasedByTutor = Lesson::query()->where('recurring_slot_id', $slot->id)->where('status', LessonStatus::CancelledByTutor)->count();
    $stillReserved = Lesson::query()->where('recurring_slot_id', $slot->id)->where('status', LessonStatus::Reserved)->count();

    expect($slot->fresh()->end_effective_on)->not->toBeNull()
        ->and($releasedByTutor)->toBeGreaterThan(0)
        ->and($stillReserved)->toBeGreaterThan(0);

    // While the notice runs the parent still sees the slot as live, with the notice flagged, and can end it.
    test()->actingAs($parent)->get(route('learners.show', $learner))
        ->assertInertia(fn ($page) => $page->where('slots.0.tutor_notice', true)->where('slots.0.status', 'active'));

    test()->actingAs($parent)->post(route('weekly-slots.end', $slot))->assertRedirect(route('learners.show', $learner));

    $slot = $slot->fresh();
    expect($slot->status)->toBe(RecurringSlotStatus::Ended)
        ->and($slot->end_effective_on)->toBeNull()
        ->and($slot->ended_by_user_id)->toBe($parent->id)
        // The tutor's earlier releases stay theirs; only what was still reserved becomes the parent's.
        ->and(Lesson::query()->where('recurring_slot_id', $slot->id)->where('status', LessonStatus::CancelledByTutor)->count())->toBe($releasedByTutor)
        ->and(Lesson::query()->where('recurring_slot_id', $slot->id)->where('status', LessonStatus::CancelledByParent)->count())->toBe($stillReserved)
        ->and(Lesson::query()->where('recurring_slot_id', $slot->id)->where('status', LessonStatus::Reserved)->count())->toBe(0);

    test()->actingAs($parent)->get(route('learners.show', $learner))
        ->assertInertia(fn ($page) => $page->where('slots.0.tutor_notice', false)->where('slots.0.status', 'ended'));
});

it('cuts a non-UTC slot off at the end of its own local day, and gives the tutor no strike', function () {
    Mail::fake();
    Settings::set('recurring_tutor_end_notice_days', 0);
    // Tuesday 02:00 in Karachi = Monday 21:00 UTC, 15 hours away: inside the cancel window too, which is
    // where a plain tutor cancellation would earn a strike.
    $setup = wpTutor('Asia/Karachi', '02:00:00', '04:00:00');
    ['learner' => $learner] = wpParent($setup['tutor']);

    $slot = RecurringSlot::factory()->create([
        'learner_id' => $learner->id,
        'tutor_profile_id' => $setup['tutor']->id,
        'curriculum_id' => $setup['curriculum_id'],
        'subject_id' => $setup['subject_id'],
        'weekday' => 2,
        'start_time' => '02:00:00',
        'timezone' => 'Asia/Karachi',
        'starts_on' => '2026-09-14',
        'generated_until' => '2026-09-13',
        'price' => 10000,
    ]);
    Artisan::call('recurring:generate');

    $first = Lesson::query()->where('recurring_slot_id', $slot->id)->orderBy('starts_at')->first();
    expect($first->starts_at->toIso8601String())->toBe('2026-09-14T21:00:00+00:00');

    test()->actingAs($setup['tutor']->user)->post(route('tutor.weekly-slots.end', $slot))->assertRedirect();

    // Today in Karachi is Monday the 14th; 21:00Z is already Tuesday there, so it is past the last day.
    expect($first->fresh()->status)->toBe(LessonStatus::CancelledByTutor)
        ->and(Lesson::query()->where('recurring_slot_id', $slot->id)->where('status', LessonStatus::Reserved)->count())->toBe(0)
        ->and(TutorStrike::query()->where('tutor_profile_id', $setup['tutor']->id)->count())->toBe(0);
});

it('still reads right when the parent ends the slot before the tutor\'s notice email is sent', function () {
    ['slot' => $slot, 'parent' => $parent, 'setup' => $setup] = wpSlotWithLessons();

    test()->actingAs($setup['tutor']->user)->post(route('tutor.weekly-slots.end', $slot))->assertRedirect();
    $lastDay = $slot->fresh()->end_effective_on->toDateString();

    // The parent ends it outright; the queued email then re-reads a slot with no notice date at all.
    app(EndRecurringSlot::class)($parent, $slot->fresh());
    $ended = $slot->fresh();
    expect($ended->end_effective_on)->toBeNull();

    $sent = (new RecurringSlotEndedMail($ended, $parent, Role::Tutor, 2, 0, $lastDay))->render();
    expect($sent)->toContain('will end after '.CarbonImmutable::parse($lastDay)->format('l, j M Y'));

    $noDate = (new RecurringSlotEndedMail($ended, $parent, Role::Tutor, 2, 0))->render();
    expect($noDate)->toContain('has been ended, following the notice the tutor gave');
});

it('carries the tutor\'s last day on the ended event, so the queued email does not have to re-derive it', function () {
    Mail::fake();
    ['slot' => $slot, 'setup' => $setup] = wpSlotWithLessons();

    test()->actingAs($setup['tutor']->user)->post(route('tutor.weekly-slots.end', $slot))->assertRedirect();
    $lastDay = $slot->fresh()->end_effective_on->toDateString();

    Mail::assertQueued(RecurringSlotEndedMail::class, fn ($m) => $m->endedBy === Role::Tutor && $m->lastDay === $lastDay);
});

it('refuses a store for a tutor who is not bookable with the same generic message', function () {
    $setup = wpTutor();
    ['parent' => $parent, 'learner' => $learner] = wpParent($setup['tutor']);
    $setup['tutor']->forceFill(['status' => TutorProfileStatus::Suspended])->save();

    test()->actingAs($parent)->post(route('weekly-slots.store'), wpForm($setup, $learner))
        ->assertSessionHasErrors(['slot' => 'That weekly slot cannot be set up.']);

    expect(RecurringSlot::query()->count())->toBe(0);
});

it('words the ended email for an admin, and uses the earlier of the two end dates for a tutor notice', function () {
    ['slot' => $slot, 'parent' => $parent] = wpSlotWithLessons();

    expect((new RecurringSlotEndedMail($slot, $parent, Role::Admin, 0, 0))->render())->toContain('was ended by the platform team');

    $slot->forceFill(['ends_on' => '2026-10-01', 'end_effective_on' => '2026-10-05'])->save();
    expect((new RecurringSlotEndedMail($slot->fresh(), $parent, Role::Tutor, 0, 0))->render())->toContain('will end after Thursday, 1 Oct 2026');
});
