<?php

namespace App\Enums;

/**
 * Machine-readable values written to `lessons.cancel_reason` (a free-text column)
 * when the platform, not a person's typed note, cancels a lesson. Only the values
 * something reads back are named here.
 */
enum LessonCancelReason: string
{
    /**
     * A weekly slot was paused (R99): the future `reserved` lessons are cancelled free
     * as `cancelled_by_parent`. The recurring-key index on `lessons` frees these rows'
     * `(recurring_slot_id, starts_at)` so that resume can regenerate the week.
     */
    case SlotPaused = 'slot_paused';

    /**
     * A weekly slot was ended (R99) by the parent, the tutor or an admin: the affected
     * `reserved` lessons are cancelled free. Unlike a pause, these rows keep their
     * `(recurring_slot_id, starts_at)` key — an ended slot is never regenerated.
     */
    case SlotEnded = 'slot_ended';

    /**
     * A weekly lesson's start time passed while it was still `reserved` and uncharged (the charge job
     * was not running, or the lesson was generated too late to charge): cancelled as
     * `cancelled_payment_failed`, but it is the platform's timing, not the parent's card, so it does
     * not count toward the slot's failure counter. The email wording reads this value.
     */
    case ChargeWindowMissed = 'charge_window_missed';

    /**
     * A weekly lesson fell due for charging while its tutor was no longer `bookable()` (suspended,
     * permit lapsed, account deleted) — R104: cancelled as `cancelled_by_tutor` with no actor, never
     * charged, no strike, and the slot stays active. It keeps its `(recurring_slot_id, starts_at)`
     * key, so a reinstated tutor's next generation run does not recreate that week. Being a machine
     * value also keeps the generic free-skip email quiet.
     */
    case TutorUnavailable = 'tutor_unavailable';

    /**
     * R138: a safeguarding suspension of the tutor (from the admin Safeguarding queue, or the
     * automatic 3-strikes path — both go through `SuspendTutor`). A `reserved` lesson is cancelled
     * free as `cancelled_by_tutor`, no strike; a `confirmed` lesson is cancelled the same way with a
     * full refund to the parent (`LessonSettlement::refundParent()`, the `MarkProviderFailure`
     * shape — no gateway call, CP5's). It keeps its `(recurring_slot_id, starts_at)` key like
     * `TutorUnavailable`: reinstating restores nothing cancelled (R138), so that week is never
     * regenerated. The tutor-facing and parent-facing mail must stay neutral — never printing this
     * value or the word "suspended" — matching `WeeklyLessonTutorUnavailableMail`'s precedent.
     */
    case TutorSuspended = 'tutor_suspended';

    /**
     * R138: the account (parent or tutor) itself was suspended from the admin Safeguarding queue.
     * A `reserved` lesson is cancelled free as `cancelled_by_parent`, no strike; a `confirmed`
     * lesson is left untouched (an admin decision, listed for them, not automated). Keeps its
     * `(recurring_slot_id, starts_at)` key, same as `TutorSuspended` — never regenerated.
     */
    case AccountSuspended = 'account_suspended';

    /**
     * R151 (CP8 admin lesson operations): an admin force-cancelled the lesson from the Filament
     * "Lessons" queue (`ForceCancelLesson`) — a distinct decision from any of the platform's own
     * automatic cancellations above. A `reserved` lesson is cancelled free as `cancelled_by_tutor`,
     * no strike, mirroring `CancelSuspendedTutorLessons`'s reserved branch; a `confirmed` lesson is
     * cancelled the same way with a full refund to the parent (`LessonSettlement::refundParent()`).
     * Being a recognised machine value keeps the generic free-skip mail/bell quiet for the reserved
     * case (same shape as `TutorUnavailable`/`TutorSuspended`) and, via `isReserved()`, keeps the raw
     * value out of the confirmed-case cancellation email (`cancelled.blade.php`'s own guard). It
     * keeps its `(recurring_slot_id, starts_at)` key like `TutorSuspended`: an admin force-cancel is
     * never auto-regenerated by the next `recurring:generate` run. The admin's required note lives
     * only in the audit log (`RecordAuditLog`'s `$after`), never on the lesson row itself.
     */
    case Admin = 'admin';

    /**
     * Whether typed text collides with a machine value. `lessons_recurring_slot_starts_at_unique`
     * frees a key by reading `cancel_reason`, so a person's own note must never be able to equal
     * one; any future typed-reason input must refuse it.
     */
    public static function isReserved(?string $text): bool
    {
        return $text !== null && self::tryFrom(trim($text)) !== null;
    }
}
